compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 8
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
fsdp_config:
  fsdp_auto_wrap_policy: SIZE_BASED_WRAP
  # The 'fsdp_transformer_layer_cls_to_wrap' parameter is NOT used with SIZE_BASED_WRAP.
  # Make sure it's removed or commented out to avoid configuration conflicts.
  fsdp_min_num_params: 10000000 # <--- Adjust this value based on your model's size and GPU memory
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_offload_param_device: cpu
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
  fsdp_cpu_ram_efficient_loading: false

